In [1]:
import numpy as np

In [2]:
lst = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
lst[-3:]

array([ 8,  9, 10])

In [18]:
x0 = 1
y0 = 2
z0 = 3
acc_array = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2],[3,4,5],[6,7,8]])
acc_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
next_acc = [10,2,4]
next_acc = np.array([next_acc[0]-x0, next_acc[1]-y0, next_acc[2]-z0])
next_acc

array([9, 0, 1])

In [20]:
acc_array[1:]

array([[4, 5, 6],
       [7, 8, 9],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
acc_array = np.append(acc_array[1:], [next_acc], axis=0)
acc_array

array([[4, 5, 6],
       [7, 8, 9],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 0, 1]])

In [27]:
acc_array[-3:,2]

array([5, 8, 1])

In [32]:
next_acc = next_acc + np.array([x0,y0,z0])*1
next_acc

array([10,  2,  4])